default_stages: [commit]
repos:
  - repo: local
    hooks:

      - id: black
        name: Black
        entry: black
        types: [python]
        language: system

      - id: system
        name: Isort
        entry: isort
        types: [python]
        language: system

      - id: pylint
        name: Pylint
        entry: pylint
        args:
          [
            "--rcfile=pyproject.toml", # Link to your config file
          ]
        types: [python]
        language: system

      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        types: [python]
        language: system
